### ISSUE TITLE
Cannot read property 'split' of null

### ISSUE THREAD

**Issue by sauravkoli31** [131/node-tld#11]
receiving the following error while trying ` parser("www.google.com")`

```
TypeError: Cannot read property 'split' of null
    at parse_host (\node_modules\tld-extract\index.js:23:20)
    at parse_url (\node_modules\tld-extract\index.js:9:10)
```

**Comment by sauravkoli31** [comment]
Issue seems to be with the url package dependency. url.parse has been deprecated.

```
function parse(urlStr: string): url.UrlWithStringQuery (+3 overloads)
@deprecated — since v11.0.0 - Use the WHATWG URL API.

The signature '(urlStr: string): UrlWithStringQuery' of 'url.parse' is deprecated.ts(6387)
url.d.ts(47, 9): The declaration was marked as deprecated here.
```

**Comment by leptoquark1** [comment]
This is not an issue if you ask @131
see https://github.com/131/node-tld/issues/7

**Comment by mfpopa** [comment]
@sauravkoli31 Even if the [url.parse](https://nodejs.org/api/url.html#url_url_parse_urlstring_parsequerystring_slashesdenotehost) is now deprecated and even if the library is updated to use `new URL('...')`, you will still have the same issue.

You just need to use the [`parse_host`](https://github.com/131/node-tld/blob/4940bc49d5a93c69be1ea227e54668cadd7f0fd6/index.js#L14) function instead. Just like @leptoquark1 suggested.

The API is:
```javascript
import parse_url, { parse_host } from 'tld-extract';

parse_url('https://www.google.com') // this requires the full URL including the protocol
parse_host('www.google.com') // expects to parse just the hostname of a URL
```
