### ISSUE TITLE
'Cannot find module './effective_tld_names.json' when packaged using browserify

### ISSUE THREAD

**Issue by MartinMay** [131/node-tld#3]
We've been using tld-extract successfully within a serverless backend service until we upgraded from 1.0.1 to 1.1.2.

we're using browserify to make our packages smaller and more efficient

We've since downgraded back to 1.0.1 as browserify fails to include effective_tld_names.json into the package, causing all service requesting that require tld-extract to fail.

**Comment by 131** [comment]
Fixed in tld-extract@1.1.4.
(sorry for not merging your code, i saw your PR after i submitted other stuffs)
Thank you !
