### ISSUE TITLE
Missing protocol results in TypeError: Cannot read property 'split' of null

### ISSUE THREAD

**Issue by leptoquark1** [131/node-tld#7]
I think the reason is that url.parse returns hostname as null when the uri string has no protocol.

https://github.com/131/node-tld/blob/abb74beb64439a11dca708041eb32e6453c48cec/index.js#L6-L10

This results in a split on null:

https://github.com/131/node-tld/blob/abb74beb64439a11dca708041eb32e6453c48cec/index.js#L23

I'd suggest to add the protocol if missing.

**Comment by 131** [comment]
Just use
```
 require('tld-extract').parse_host('foo.bar')
 ```
