### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by mfpopa** [131/node-tld#9]
I am using this library with TypeScript. Because there are no types, I have written my own. The API is small, so it was not big deal.

I think there may be other people using this library in a TypeScript code base, so I am thinking whether you would accept a **pull request for a TypeScript definition file**?

I am happy to maintain it for future changes. I can also create tests for the types using [tsd](https://www.npmjs.com/package/tsd)

**Comment by 131** [comment]
I'll gladly merge it

**Comment by mfpopa** [comment]
Awesome. I will create a pull request by the end of the week.

**Comment by aitorres** [comment]
Hello! I was wondering if there are plans to merge the linked PR and solve this issue in the short term. Thanks!

**Comment by grug** [comment]
For anyone wanting a TypeScript version of this library, I've modernised a few things and tidied some stuff up here: https://www.npmjs.com/package/extract-tld

Full credit to 131, once the TS changes get merged into this library, I'll take mine down.

**Comment by oleg-koval** [comment]
Any news on merging typescript changes? :) 🆙 🆙
